#!/bin/bash

#   sysinfo_page - A script to produce an html file

cat << _EOF_
<html>
<head>
    <title>
    The title of your page
    </title>
</head>

<body>
    Your page goes here.
</body>
</html>
_EOF_
