#!/bin/bash

echo "
CC=g++
CFLAGS=-c -Wall -Werror
LDFLAGS=
SOURCES=
OBJECTS=\$(SOURCES:.cc=.o)
EXECUTABLE=main

all: \$(SOURCES) \$(EXECUTABLE)

\$(EXECUTABLE): \$(OBJECTS)
	\$(CC) \$(LDFLAGS) \$(OBJECTS) -o \$@

.cc.o:
	\$(CC) \$(CFLAGS) $< -o \$@

clean:
	rm \$(OBJECTS) \$(EXECUTABLE)

" > Makefile
